import type { NextPage } from 'next';
import Head from 'next/head';
import styled, { css } from 'styled-components';
import styles from '../styles/Home.module.scss';

const StyledP = styled('p')<{textColor ?: string}>(({ textColor = 'black' }) => css`
color: ${textColor};
`);

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className="text-3xl font-bold underline">
        Welcome to
        {' '}
        <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <StyledP textColor="blue">
        ppppppppppppp
      </StyledP>
      <StyledP>
        pppppppppppppsss
      </StyledP>
      <p className={styles.para}>
        helloooo
      </p>

    </main>

  </div>
);

export default Home;
